database:
    message:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/wxpublicapi_12?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_01?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_02?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_03?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_04?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_05?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_06?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_07?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_08?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_09?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_10?useUnicode=true&characterEncoding=utf-8&useSSL=false,jdbc:mysql://localhost:3306/wxpublicapi_11?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123.com
        tb: t_message_0,t_message_1,t_message_2,t_message_3,t_message_4,t_message_5,t_message_6,t_message_7,t_message_8,t_message_9
        tbName: t_message
        tbKey: receive_date
    qs:
        username: root
        password: 123.com
        url: jdbc:mysql://localhost:3306/qs?useUnicode=true&charaterEncoding=utf-8&useSSL=false
        driver: com.mysql.jdbc.Driver
mybatis:
    message:
        typeAliasesPackage: com.weimob.bs.multidb.dao.mysql.model
---
spring:
    profiles.active: @spring.profiles@
---
spring:
    profiles: dev
database:
    message:
        password: 123.com
---
spring:
    profiles: pl
database:
    message:
        password: 123.com
---
spring:
    profiles: online
database:
    message:
        password: 123.com

